---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "{'ballena': 7, 'gallina': 7, 'elefante': 8}"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "{'ballena': 3, 'gallina': 3, 'elefante': 3}"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "{3: ['ballena', 'gallina',  'elefante']}"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "{['ballena', 'gallina',  'elefante']:3}"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Devuelve error, ya la lista no puede ser una llave.
  checked: false
name: Diccionario de animales
